
clean:
	rm -f jmcdm-paper.bbl
	rm -f jmcdm-paper.log
	rm -f jmcdm-paper.synctex.gz
	rm -f jmcdm-paper.out
	rm -f jmcdm-paper.fdb_latexmk
	rm -f jmcdm-paper.aux
	rm -f jmcdm-paper.fls
	rm -f jmcdm-paper.spl
	rm -f jmcdm-paper.blg

pdf:
	pdflatex jmcdm-paper.tex

